name: matml
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.9.*
  - numpy==1.22.*
  - pandas==1.*
  - scikit-learn==0.23.*
  - matplotlib==3.*
  - pymatgen==2022.1.24
  - tqdm
  - jupyterlab
  - psutil
  - pytest
  - pip
  - pip:
    - matminer==0.7.*
